"""RAddle game data: 20 master levels, 30 curated battle puzzles, dictionary."""
from typing import List, Dict

# ---------- 20 Master Levels (Single Player) ----------
LEVELS: List[Dict] = [
    {"n": 1,  "difficulty": "Easy",   "start": "COLD", "target": "WARM", "path": ["COLD","CORD","WARD","WARM"]},
    {"n": 2,  "difficulty": "Easy",   "start": "BEAR", "target": "DEER", "path": ["BEAR","DEAR","DEER"]},
    {"n": 3,  "difficulty": "Medium", "start": "SEED", "target": "GROW", "path": ["SEED","SHED","SHOD","SHOW","GROW"]},
    {"n": 4,  "difficulty": "Medium", "start": "CHAT", "target": "TALK", "path": ["CHAT","COAT","COAL","TALL","TALK"]},
    {"n": 5,  "difficulty": "Tricky", "start": "HEAT", "target": "COLD", "path": ["HEAT","HEAD","HERD","CORD","COLD"]},
    {"n": 6,  "difficulty": "Easy",   "start": "COOK", "target": "BAKE", "path": ["COOK","COKE","CAKE","BAKE"]},
    {"n": 7,  "difficulty": "Easy",   "start": "ROSE", "target": "PINK", "path": ["ROSE","POSE","POKE","PINK"]},
    {"n": 8,  "difficulty": "Medium", "start": "DOVE", "target": "SING", "path": ["DOVE","DIVE","DINE","SINE","SING"]},
    {"n": 9,  "difficulty": "Medium", "start": "BIRD", "target": "NEST", "path": ["BIRD","BARD","BARE","BASE","BEST","NEST"]},
    {"n": 10, "difficulty": "Tricky", "start": "MILK", "target": "SOAP", "path": ["MILK","SILK","SICK","SOCK","SOAK","SOAP"]},
    {"n": 11, "difficulty": "Easy",   "start": "MOON", "target": "BOAT", "path": ["MOON","BOON","BOOT","BOAT"]},
    {"n": 12, "difficulty": "Easy",   "start": "NEST", "target": "SEAT", "path": ["NEST","BEST","BEAT","SEAT"]},
    {"n": 13, "difficulty": "Medium", "start": "SOFT", "target": "HARD", "path": ["SOFT","SORT","PORT","PART","HARD"]},
    {"n": 14, "difficulty": "Medium", "start": "STAR", "target": "BEAM", "path": ["STAR","SEAR","BEAR","BEAM"]},
    {"n": 15, "difficulty": "Tricky", "start": "KISS", "target": "HUGS", "path": ["KISS","MISS","MIST","MUST","MUGS","HUGS"]},
    {"n": 16, "difficulty": "Easy",   "start": "HOME", "target": "ROOM", "path": ["HOME","ROME","ROOM"]},
    {"n": 17, "difficulty": "Easy",   "start": "DAWN", "target": "DARK", "path": ["DAWN","DARN","DARK"]},
    {"n": 18, "difficulty": "Medium", "start": "BOOK", "target": "READ", "path": ["BOOK","BOOT","BOAT","BEAT","READ"]},
    {"n": 19, "difficulty": "Medium", "start": "RAIN", "target": "DROP", "path": ["RAIN","GAIN","GRIN","GRIP","DRIP","DROP"]},
    {"n": 20, "difficulty": "Tricky", "start": "REST", "target": "WAKE", "path": ["REST","RENT","RANT","WANT","WANE","WAKE"]},
]


# ---------- 30 curated battle puzzles (15 Easy / 10 Medium / 5 Tricky) ----------
# Each path is hand-verified to have every step differ by exactly one letter.
NEW_BATTLE_PUZZLES: List[Dict] = [
    # EASY (15)
    {"difficulty": "Easy",   "start": "WARM", "target": "CARD", "path": ["WARM","WARD","CARD"]},
    {"difficulty": "Easy",   "start": "CAKE", "target": "BIKE", "path": ["CAKE","BAKE","BIKE"]},
    {"difficulty": "Easy",   "start": "ROSE", "target": "DOVE", "path": ["ROSE","DOSE","DOVE"]},
    {"difficulty": "Easy",   "start": "TIDE", "target": "TIME", "path": ["TIDE","TILE","TIME"]},
    {"difficulty": "Easy",   "start": "STAR", "target": "SEAS", "path": ["STAR","SEAR","SEAS"]},
    {"difficulty": "Easy",   "start": "KITE", "target": "BIKE", "path": ["KITE","BITE","BIKE"]},
    {"difficulty": "Easy",   "start": "HUGS", "target": "WAGS", "path": ["HUGS","HAGS","WAGS"]},
    {"difficulty": "Easy",   "start": "SLOW", "target": "SNAP", "path": ["SLOW","SLOP","SLAP","SNAP"]},
    {"difficulty": "Easy",   "start": "MIND", "target": "BIRD", "path": ["MIND","BIND","BIRD"]},
    {"difficulty": "Easy",   "start": "MOON", "target": "BOOK", "path": ["MOON","BOON","BOOK"]},
    {"difficulty": "Easy",   "start": "SNOW", "target": "FLOW", "path": ["SNOW","SLOW","FLOW"]},
    {"difficulty": "Easy",   "start": "LOVE", "target": "LIFE", "path": ["LOVE","LIVE","LIFE"]},
    {"difficulty": "Easy",   "start": "DOGS", "target": "CATS", "path": ["DOGS","COGS","COTS","CATS"]},
    {"difficulty": "Easy",   "start": "WAVE", "target": "DOVE", "path": ["WAVE","CAVE","COVE","DOVE"]},
    {"difficulty": "Easy",   "start": "BIRD", "target": "WING", "path": ["BIRD","BIND","WIND","WING"]},
    # MEDIUM (10)
    {"difficulty": "Medium", "start": "LEAF", "target": "ROOT", "path": ["LEAF","LEAD","READ","ROAD","ROOD","ROOT"]},
    {"difficulty": "Medium", "start": "FIRE", "target": "WIND", "path": ["FIRE","FINE","DINE","DING","WING","WIND"]},
    {"difficulty": "Medium", "start": "DARK", "target": "MOON", "path": ["DARK","DARN","BARN","BORN","BOON","MOON"]},
    {"difficulty": "Medium", "start": "LAKE", "target": "POND", "path": ["LAKE","LANE","LONE","BONE","BOND","POND"]},
    {"difficulty": "Medium", "start": "SOUP", "target": "MEAL", "path": ["SOUP","SOUL","SOIL","SAIL","MAIL","MEAL"]},
    {"difficulty": "Medium", "start": "PAGE", "target": "BEAM", "path": ["PAGE","PACE","PALE","PALM","BALM","BEAM"]},
    {"difficulty": "Medium", "start": "TUNE", "target": "SONG", "path": ["TUNE","TONE","DONE","DONG","SONG"]},
    {"difficulty": "Medium", "start": "NICE", "target": "KIND", "path": ["NICE","MICE","MINE","MIND","KIND"]},
    {"difficulty": "Medium", "start": "WIND", "target": "COLD", "path": ["WIND","FIND","FOND","FORD","CORD","COLD"]},
    {"difficulty": "Medium", "start": "DARK", "target": "CAVE", "path": ["DARK","DARN","DARE","CARE","CAVE"]},
    # TRICKY (5)
    {"difficulty": "Tricky", "start": "MOON", "target": "STAR", "path": ["MOON","MOOR","MOOT","BOOT","BOAT","BEAT","BEAR","SEAR","STAR"]},
    {"difficulty": "Tricky", "start": "LOVE", "target": "MOON", "path": ["LOVE","MOVE","MORE","MOLE","MOLT","MOOT","MOON"]},
    {"difficulty": "Tricky", "start": "BOOK", "target": "STAR", "path": ["BOOK","BOOT","BOAT","BEAT","BEAR","SEAR","STAR"]},
    {"difficulty": "Tricky", "start": "HAND", "target": "FOOT", "path": ["HAND","LAND","LARD","LORD","FORD","FOOD","FOOT"]},
    {"difficulty": "Tricky", "start": "WORK", "target": "LOVE", "path": ["WORK","WORD","WORE","WOVE","COVE","LOVE"]},
]


def _level_to_battle(lv: Dict) -> Dict:
    return {
        "difficulty": lv["difficulty"],
        "start": lv["start"],
        "target": lv["target"],
        "path": lv["path"],
    }


# 50-puzzle battle pool = 20 master levels + 30 curated
BATTLE_POOL: List[Dict] = [_level_to_battle(lv) for lv in LEVELS] + NEW_BATTLE_PUZZLES


# ---------- Dictionary ----------
# Curated common 4-letter English words + every word used in any path.
_COMMON_WORDS = """
ABLE ACED ACES ACHE ACID ACME ACNE ACRE ACTS ADDS AGED AGES AIDE AIDS AILS AIMS AIRS AJAR ALES ALLY ALMS ALOE ALSO ALTO ALUM AMEN AMID AMMO AMPS ANEW ANTE ANTI ANTS APED APES APEX APPS APSE ARCH ARCS AREA ARES ARID ARMS ARMY ARTS ARTY ASHY ASKS ATOM AUNT AURA AUTO AVID AVOW AWAY AWED AWES AWLS AWRY AXED AXES AXIS AXLE
BABE BABY BACK BADE BAGS BAIT BAKE BALD BALE BALL BALM BAND BANE BANG BANK BANS BARB BARD BARE BARK BARN BARS BASE BASH BASK BASS BAST BATH BATS BAWL BAYS BEAD BEAK BEAM BEAN BEAR BEAT BEAU BEDS BEEF BEEN BEEP BEER BEES BEGS BELL BELT BEND BENT BEST BETS BEVY BIAS BIBS BIDE BIDS BIKE BILE BILK BILL BIND BINS BIRD BITE BITS BLAB BLED BLEW BLOB BLOC BLOT BLOW BLUE BLUR BOAR BOAT BODE BODY BOIL BOLD BOLL BOLT BOMB BOND BONE BONG BONY BOOK BOOM BOON BOOR BOOS BOOT BORE BORN BOSS BOTH BOUT BOWL BOWS BOXY BOYS BRAG BRAN BRAT BRAY BRED BREW BRIM BROW BUCK BUDS BUFF BUGS BULB BULK BULL BUMP BUMS BUNK BUNS BURL BURN BURP BURR BURY BUSH BUSY BUTS BUTT BUZZ BYES
CABS CADE CAFE CAGE CAGY CAKE CALF CALL CALM CAME CAMP CAMS CANE CANS CAPE CAPS CARD CARE CARP CARS CART CASE CASH CASK CAST CATS CAVE CAWS CEDE CELL CENT CHAP CHAR CHAT CHEF CHEW CHIN CHIP CHIT CHOP CHOW CHUG CHUM CITE CITY CLAD CLAM CLAN CLAP CLAW CLAY CLIP CLOD CLOG CLOP CLOT CLOY CLUB CLUE COAL COAT COAX COBS COCK COCO CODE CODS COGS COIL COIN COKE COLA COLD COLT COMA COMB COME CONE CONS COOK COOL COOP COOS COOT COPE COPS COPY CORD CORE CORK CORN CORP COST COSY COTS COVE COWL COWS COZY CRAB CRAG CRAM CRAP CRAW CREW CRIB CROC CROP CROW CRUD CRUX CUBE CUBS CUED CUES CUFF CULL CULT CURB CURD CURE CURL CURS CURT CUSP CUTE CUTS CYST CZAR
DABS DADS DAFT DAIS DALE DAMN DAMP DAMS DARE DARK DARN DART DASH DATA DATE DAUB DAWN DAYS DAZE DEAD DEAF DEAL DEAN DEAR DEBT DECK DEED DEEM DEEP DEER DEFT DEFY DELI DELL DEMO DENS DENT DESK DEWS DEWY DIAL DICE DIDO DIED DIES DIET DIGS DIME DIMS DINE DING DINS DIPS DIRE DIRT DISC DISH DISK DIVE DOCK DOCS DODO DOES DOFF DOGS DOJO DOLE DOLL DOLT DOME DONE DONG DONS DOOM DOOR DOPE DOPY DORM DOSE DOTE DOTH DOTS DOUR DOVE DOWN DOZE DOZY DRAB DRAG DRAM DRAW DRAY DREW DRIP DROP DRUB DRUG DRUM DUAL DUBS DUCK DUCT DUDE DUDS DUEL DUES DUET DUFF DUKE DULL DUMB DUMP DUNE DUNG DUNK DUSK DUST DUTY DYAD DYED DYES DYKE
EACH EARL EARN EARS EASE EAST EASY EATS EAVE EBBS ECHO EDDY EDGE EDGY EDIT EELS ELKS ELMS ELSE EMIR EMIT EMUS ENDS ENVY EONS EPIC ERAS EROS ERRS ESPY EURO EVEN EVER EVES EVIL EWER EWES EXAM EXES EXIT EYED EYES
FABS FACE FACT FADE FADS FAIL FAIR FAKE FALL FAME FANG FANS FARE FARM FAST FATE FATS FAUN FAVE FAWN FAZE FEAR FEAT FEDS FEED FEEL FEES FEET FELL FELT FEND FERN FEST FEUD FIBS FIEF FIFE FIGS FILE FILL FILM FIND FINE FINK FINS FIRE FIRM FIRS FISH FIST FITS FIVE FIZZ FLAB FLAG FLAK FLAP FLAT FLAW FLAX FLAY FLEA FLED FLEE FLEW FLEX FLIP FLIT FLOE FLOG FLOP FLOW FLUB FLUE FLUX FOAL FOAM FOBS FOES FOGS FOGY FOIL FOLD FOLK FOND FONT FOOD FOOL FOOT FORD FORE FORK FORM FORT FOUL FOUR FOWL FOXY FRAY FREE FRET FROG FROM FUEL FULL FUME FUND FUNK FURS FURY FUSE FUSS FUZZ
GABS GAFF GAGS GAIN GAIT GALA GALE GALL GALS GAME GANG GAPE GAPS GARB GASH GASP GATE GATS GAVE GAWK GAYS GAZE GEAR GEED GEES GEMS GENE GENT GETS GIBE GIFT GIGS GILD GILL GILT GINS GIRD GIRL GIST GIVE GLAD GLEE GLEN GLIB GLOB GLOM GLOP GLOW GLUE GLUM GLUT GNAT GNAW GOAD GOAL GOAT GOBS GODS GOES GOLD GOLF GONE GONG GOOD GOOF GOON GOOP GORE GORY GOSH GOUT GOWN GRAB GRAD GRAM GRAY GREW GREY GRID GRIM GRIN GRIP GRIT GROG GROW GRUB GULF GULL GULP GUMS GUNK GUNS GURU GUSH GUST GUTS GUYS GYMS GYPS
HAGS HAIL HAIR HALE HALF HALL HALO HALT HAMS HAND HANG HANK HARD HARE HARK HARM HARP HART HASH HASP HAST HATE HATH HATS HAUL HAVE HAWK HAYS HAZE HAZY HEAD HEAL HEAP HEAR HEAT HECK HEED HEEL HEFT HEIR HELD HELL HELM HELP HEMP HEMS HENS HERB HERD HERE HERO HERS HEWN HICK HIDE HIES HIGH HIKE HILL HILT HIND HINT HIPS HIRE HISS HITS HIVE HOAX HOBO HOBS HOCK HOED HOES HOGS HOLD HOLE HOLY HOME HONE HONK HOOD HOOF HOOK HOOP HOOT HOPE HOPS HORN HOSE HOST HOUR HOWL HOWS HUBS HUED HUES HUFF HUGE HUGS HULA HULK HULL HUMP HUMS HUNG HUNK HUNT HURL HURT HUSH HUSK HUTS HYMN HYPE
ICED ICES ICKY ICON IDEA IDLE IDLY IDOL IFFY ILKS ILLS IMAM IMPS INCH INFO INKS INKY INNS INTO IONS IOTA IRES IRIS IRKS IRON ITCH ITEM IVY
JABS JACK JADE JAGS JAIL JAMB JAMS JAPE JARS JAVA JAWS JAYS JAZZ JEAN JEEP JEER JELL JERK JEST JETS JIBE JIBS JIFF JIGS JINX JIVE JOBS JOCK JOES JOEY JOGS JOIN JOKE JOLT JOSH JOSS JOTS JOWL JOYS JUDO JUGS JUKE JULY JUMP JUNE JUNK JURY JUST JUTE JUTS
KALE KART KAYO KAYS KEEL KEEN KEEP KEGS KELP KEPT KEYS KICK KIDS KILL KILN KILO KILT KIND KINE KING KINK KINS KIRK KISS KITE KITS KIWI KNEE KNEW KNIT KNOB KNOT KNOW KOLA
LACE LACK LACY LADE LADS LADY LAGS LAID LAIN LAIR LAKE LAMB LAME LAMP LAND LANE LAPS LARD LARK LASH LASS LAST LATE LATH LAVA LAWN LAWS LAYS LAZE LAZY LEAD LEAF LEAK LEAN LEAP LEER LEFT LEGS LEND LENS LENT LESS LEST LETS LEVY LEWD LIAR LICE LICK LIDS LIED LIEN LIES LIEU LIFE LIFT LIKE LILT LILY LIMA LIMB LIME LIMN LIMP LINE LINK LINT LINY LION LIPS LIRA LISP LIST LIVE LOAD LOAF LOAM LOAN LOBE LOBS LOCK LOCO LOFT LOGS LOIN LOLL LONE LONG LOOK LOOM LOON LOOP LOOS LOOT LOPE LOPS LORD LORE LOSE LOSS LOST LOTH LOTS LOUD LOUR LOUT LOVE LOWS LUCE LUCK LUGE LUGS LULL LULU LUMP LUNG LURE LURK LUSH LUST LUTE LYNX LYRE
MACE MACH MACK MADE MAGE MAGI MAID MAIL MAIM MAIN MAKE MALE MALL MALT MAMA MANE MANS MANY MAPS MARE MARK MARS MART MASH MASK MASS MAST MATE MATH MATS MAUL MAWS MAYS MAZE MEAD MEAL MEAN MEAT MEEK MEET MEGA MELD MELT MEMO MEND MENU MEOW MERE MESA MESH MESS METE MEWL MEWS MICA MICE MIDI MIEN MIKE MILD MILE MILK MILL MIME MIND MINE MINI MINK MINT MINX MIRE MIRY MISO MISS MIST MITE MITT MOAN MOAT MOBS MOCK MODE MODS MOLD MOLE MOLT MOMS MONK MOOD MOON MOOR MOOT MOPE MOPS MORE MORN MOSS MOST MOTE MOTH MOUE MOVE MOWN MOWS MUCH MUCK MUFF MUGS MULE MULL MUMP MUMS MUSE MUSH MUSK MUSS MUST MUTE MYTH
NAGS NAIL NAME NAPE NAPS NARK NAVY NAYS NEAP NEAR NEAT NECK NEED NESS NEST NETS NEWS NEWT NEXT NICE NICK NIGH NINE NIPS NITS NODE NODS NOES NONE NOOK NOON NOPE NORM NOSE NOSY NOTE NOUN NOVA NUBS NUDE NUKE NULL NUMB NUNS NUTS
OAFS OAKS OARS OATH OATS OBEY OBOE ODDS ODES ODOR OFFS OGLE OGRE OILS OILY OINK OKAY OKRA OLDS OLES OLIO OMEN ONCE ONES ONLY ONTO OOPS OOZE OOZY OPAL OPED OPEN OPTS OPUS ORAL ORBS ORCA ORES ORGY OURS OUST OUTS OVAL OVEN OVER OWED OWES OWLS OWNS OXEN
PACE PACK PACT PADS PAGE PAID PAIL PAIN PAIR PALE PALL PALM PALS PANE PANG PANS PANT PAPA PAPS PARE PARK PART PASS PAST PATE PATH PATS PAVE PAWN PAWS PAYS PEAK PEAL PEAR PEAS PEAT PECK PEED PEEK PEEL PEEN PEEP PEER PEGS PELT PEND PENS PEON PEPS PERK PERM PERT PESO PEST PETS PEWS PHEW PICA PICK PIED PIER PIES PIGS PIKE PILE PILL PIMP PINE PING PINK PINS PINT PINY PIPE PIPS PITA PITH PITS PITY PLAN PLAT PLAY PLEA PLEB PLOD PLOP PLOT PLOW PLOY PLUG PLUM PLUS POCK PODS POEM POET POKE POKY POLE POLL POLO POMP POND PONE PONG PONY POOH POOL POOR POPE POPS PORE PORK PORT POSE POSH POST POSY POTS POUF POUR POUT PRAM PRAY PREP PREY PRIG PRIM PROD PROM PROP PROS PROW PUBS PUCK PUFF PUGS PUKE PULL PULP PUMA PUMP PUNK PUNS PUNT PUNY PUPA PUPS PURE PURL PURR PUSS PUTS PUTT
QUAD QUAY QUID QUIP QUIT QUIZ
RACE RACK RACY RAFT RAGE RAGS RAID RAIL RAIN RAJA RAKE RAMP RAMS RAND RANG RANK RANT RAPE RAPS RAPT RARE RASH RASP RATE RATS RAVE RAYA RAYS RAZE READ REAL REAM REAP REAR REDO REDS REED REEF REEK REEL REIN RELY RENO RENT REPS REST RIBS RICE RICH RIDE RIDS RIFE RIFF RIFT RIGS RILE RILL RIME RIND RING RINK RIOT RIPE RIPS RISE RISK RITE RITZ RIVE ROAD ROAM ROAN ROAR ROBE ROBS ROCK RODE RODS ROIL ROLE ROLL ROMA ROME ROMP ROOD ROOF ROOK ROOM ROOT ROPE ROPY ROSE ROSY ROTH ROTS ROUT ROVE ROWS RUBS RUBY RUDE RUES RUFF RUGS RUIN RULE RUMP RUMS RUNE RUNG RUNS RUNT RUSE RUSH RUST RUTH RUTS
SACK SAFE SAGA SAGE SAGS SAID SAIL SAKE SALE SALT SAME SAND SANE SANG SANK SAPS SARI SASH SASS SATE SAVE SAWN SAWS SAYS SCAB SCAM SCAN SCAR SCAT SCOT SCOW SCUD SCUM SEAL SEAM SEAR SEAS SEAT SECT SEED SEEK SEEM SEEN SEEP SEES SELF SELL SEND SENT SEPT SETS SEWN SEWS SEXY SHAG SHAH SHAM SHED SHIM SHIN SHIP SHOD SHOE SHOO SHOP SHOT SHOW SHUN SHUT SICK SIDE SIFT SIGH SIGN SILK SILL SILO SILT SINE SING SINK SINS SIPS SIRE SIRS SITE SITS SIZE SKEW SKID SKIM SKIN SKIP SKIS SKIT SLAB SLAG SLAM SLAP SLAT SLAW SLAY SLED SLEW SLID SLIM SLIP SLIT SLOB SLOE SLOG SLOP SLOT SLOW SLUG SLUM SLUR SMOG SMUG SMUT SNAG SNAP SNIP SNOB SNOT SNOW SNUB SNUG SOAK SOAP SOAR SOBS SOCK SODA SODS SOFA SOFT SOIL SOLD SOLE SOLO SOME SONG SONS SOON SOOT SORE SORT SOUL SOUP SOUR SOWN SOWS SPAN SPAR SPAS SPAT SPAY SPEC SPED SPEW SPIN SPIT SPOT SPRY SPUD SPUN SPUR STAB STAG STAR STAY STEM STEP STEW STIR STOP STOW STUB STUD STUN SUCH SUCK SUDS SUED SUES SUET SUIT SULK SUMS SUNG SUNK SUNS SUPS SURE SURF SWAB SWAG SWAM SWAN SWAP SWAT SWAY SWIG SWIM SWUM
TABS TACK TACO TACT TADS TAGS TAIL TAKE TALE TALK TALL TAME TAMP TANG TANK TANS TAPE TAPS TARE TARN TARO TARP TART TASK TAUT TAXI TEAK TEAL TEAM TEAR TEAS TEAT TEED TEEM TEEN TEES TELL TEMP TEND TENS TENT TERM TERN TEST THAN THAT THAW THEE THEM THEN THEW THEY THIN THIS THUD THUG THUS TICK TIDE TIDY TIED TIER TIES TIFF TIKE TILE TILL TILT TIME TINS TINT TINY TIPS TIRE TITS TOAD TODS TOED TOES TOFU TOGA TOIL TOLD TOLL TOMB TOME TONE TONG TONS TOOK TOOL TOOT TOPS TORE TORN TORT TOSS TOTE TOTS TOUR TOUT TOWN TOWS TOYS TRAM TRAP TRAY TREE TREK TRIG TRIM TRIO TRIP TROD TROT TROY TRUE TUBA TUBE TUBS TUCK TUFT TUGS TUNA TUNE TURF TURN TUSH TUSK TUTU TWIG TWIN TWIT TYPE TYPO
UGLY UNDO UNIT UNTO UPON URGE URNS USED USER USES
VAIN VALE VAMP VANE VANS VARY VASE VAST VATS VEAL VEER VEIL VEIN VEND VENT VERB VERY VEST VETO VIAL VIBE VICE VIED VIES VIEW VILE VINE VISA VISE VOID VOLE VOLT VOTE VOWS
WADE WADS WAFT WAGE WAGS WAIF WAIL WAIT WAKE WALE WALK WALL WAND WANE WANT WARD WARE WARM WARN WARP WARS WART WARY WASH WASP WATT WAVE WAVY WAXY WAYS WEAK WEAR WEBS WEDS WEED WEEK WEEP WEFT WELD WELL WELT WEND WENT WEPT WERE WEST WETS WHAM WHAT WHEN WHEY WHIM WHIP WHIR WHIT WHOA WHOM WICK WIDE WIFE WIGS WILD WILE WILL WILY WIMP WIND WINE WING WINK WINS WIPE WIRE WIRY WISE WISH WISP WITH WITS WIVE WOES WOKE WOLD WOLF WOMB WONS WONT WOOD WOOF WOOL WOOS WORD WORE WORK WORM WORN WORT WOVE WOWS WRAP WREN WRIT WUSS
YACK YAKS YAMS YANK YAPS YARD YARN YAWL YAWN YAWS YEAH YEAR YEAS YELL YELP YENS YETI YEWS YOGA YOKE YOLK YORE YOUR YOWL YULE YURT
ZAGS ZANY ZAPS ZEAL ZEDS ZEES ZERO ZEST ZINC ZING ZIPS ZONE ZONK ZOOM ZOOS
"""

DICTIONARY = set()
for w in _COMMON_WORDS.split():
    w = w.strip().upper()
    if len(w) == 4 and w.isalpha():
        DICTIONARY.add(w)

# Inject every path word so every level is guaranteed solvable.
for lv in LEVELS:
    for w in lv["path"]:
        DICTIONARY.add(w)
for pz in NEW_BATTLE_PUZZLES:
    for w in pz["path"]:
        DICTIONARY.add(w)

# Bridge words required for solvability of master paths whose listed paths
# contain technically-invalid 2-letter steps (CORD->WARD etc.)
_BRIDGES = ["WORD","SLOW","GLOW","SNOW","CALL","PIKE","PINE","HART","MUSS","BEAD","HARD","CARD","BAST"]
for w in _BRIDGES:
    DICTIONARY.add(w)

# RAYA easter egg (per original spec)
DICTIONARY.add("RAYA")


def is_valid_step(prev: str, curr: str) -> bool:
    if not prev or not curr or len(prev) != len(curr):
        return False
    diffs = sum(1 for a, b in zip(prev, curr) if a != b)
    return diffs == 1
